import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useQuery } from '@tanstack/react-query';
import { Link } from 'react-router-dom';
import { fetchApi } from '../lib/api';
import StatusBadge from '../components/StatusBadge';
export default function ApplicationsList() {
    const { data: response, isLoading } = useQuery({
        queryKey: ['applications'],
        queryFn: async () => fetchApi('/applications')
    });
    return (_jsxs("div", { className: "p-8 max-w-7xl mx-auto", children: [_jsx("div", { className: "flex justify-between items-center mb-6", children: _jsx("h1", { className: "text-2xl font-bold", children: "My Applications" }) }), isLoading ? _jsx("p", { children: "Loading..." }) : (_jsx("div", { className: "bg-white shadow rounded overflow-hidden", children: _jsxs("table", { className: "w-full text-left border-collapse", children: [_jsx("thead", { className: "bg-gray-50 text-gray-700 border-b", children: _jsxs("tr", { children: [_jsx("th", { className: "p-4 font-medium", children: "Company" }), _jsx("th", { className: "p-4 font-medium", children: "Role" }), _jsx("th", { className: "p-4 font-medium", children: "Match" }), _jsx("th", { className: "p-4 font-medium", children: "Status" }), _jsx("th", { className: "p-4 font-medium", children: "Applied At" }), _jsx("th", { className: "p-4 font-medium", children: "Source" }), _jsx("th", { className: "p-4 font-medium", children: "Resume V." }), _jsx("th", { className: "p-4 font-medium", children: "Actions" })] }) }), _jsxs("tbody", { className: "divide-y divide-gray-200", children: [response?.applications?.map((app) => ( // eslint-disable-line @typescript-eslint/no-explicit-any
                                _jsxs("tr", { className: "hover:bg-gray-50", children: [_jsx("td", { className: "p-4 font-medium text-gray-900", children: app.job.company?.name || 'N/A' }), _jsx("td", { className: "p-4 text-gray-800", children: app.job.title }), _jsx("td", { className: "p-4 font-semibold text-indigo-600", children: app.job.analysis?.matchScore || 0 }), _jsx("td", { className: "p-4", children: _jsx(StatusBadge, { status: app.status }) }), _jsx("td", { className: "p-4 text-gray-500 text-sm", children: new Date(app.createdAt).toLocaleDateString() }), _jsx("td", { className: "p-4 text-gray-500 text-sm", children: app.job.source?.name || 'Unknown' }), _jsx("td", { className: "p-4 text-gray-500 text-sm", children: app.resumeVersions?.[0] ? `v${app.resumeVersions[0].version}` : '-' }), _jsx("td", { className: "p-4", children: _jsx(Link, { to: `/applications/${app.id}`, className: "text-indigo-600 hover:text-indigo-900 font-medium", children: "View Timeline" }) })] }, app.id))), response?.applications?.length === 0 && (_jsx("tr", { children: _jsx("td", { colSpan: 8, className: "text-center p-8 text-gray-500", children: "No applications found" }) }))] })] }) }))] }));
}
